### PR TITLE
Refactoring of Agda Main, and addition of Counting Mode.

### PR DESCRIPTION
**Pull request by mjaskelioff**
This PRs cleans up the `Main.lagda` file by moving functions into two new files: `Evaluator/Program.lagda.md` (used by `plc-agda` to run programs) and `Evaluator/Term.lagda.md`, used by Haskell programs to run terms in Agda. 

It adds a new function to be called from Haskell `runUCostingAgda`, which takes a `CostModel` and a UPLC term and returns a tuple consisting of the result of executing the CEK machine, the CPU cost (as an `Integer`) and memory costs (as an `Integer`). The cost model is a pair `(CekMachineCosts , BuiltinCostMap)` of machine parameters (for example `defaultCekMachineCosts`) and a map `[(Text, CpuAndMemoryModel)]` from builtin names to its cost model. This map can me obtained by calling the `getJSONModel` function in the `Cost/JSON.hs` file.

Because of the restructuring of the files, Haskell programs which wish to call `runUAgda` should now import `MAlonzo.Code.Evaluator.Term`.

### CODE REVIEW

**Review by kwxm — APPROVED** [review]
Looks fine, as far as I can tell.

**Comment by kwxm** [comment]
This seems to have broken `master`!  It passed CI, so that's a bit weird.

**Comment by kwxm** [comment]
This was failing in `master` with 
```
Preprocessing library 'plutus-benchmark-common' for plutus-benchmark-0.1.0.0..
Building library 'plutus-benchmark-common' for plutus-benchmark-0.1.0.0..
[1 of 4] Compiling Paths_plutus_benchmark ( dist/build/plutus-benchmark-common/autogen/Paths_plutus_benchmark.hs, dist/build/plutus-benchmark-common/Paths_plutus_benchmark.o, dist/build/plutus-benchmark-common/Paths_plutus_benchmark.dyn_o )
[2 of 4] Compiling PlutusBenchmark.NaturalSort ( common/PlutusBenchmark/NaturalSort.hs, dist/build/plutus-benchmark-common/PlutusBenchmark/NaturalSort.o, dist/build/plutus-benchmark-common/PlutusBenchmark/NaturalSort.dyn_o )
[3 of 4] Compiling PlutusBenchmark.ProtocolParameters ( common/PlutusBenchmark/ProtocolParameters.hs, dist/build/plutus-benchmark-common/PlutusBenchmark/ProtocolParameters.o, dist/build/plutus-benchmark-common/PlutusBenchmark/ProtocolParameters.dyn_o )
[4 of 4] Compiling PlutusBenchmark.Common ( common/PlutusBenchmark/Common.hs, dist/build/plutus-benchmark-common/PlutusBenchmark/Common.o, dist/build/plutus-benchmark-common/PlutusBenchmark/Common.dyn_o )

common/PlutusBenchmark/Common.hs:41:27: error:
    Module ‘MAlonzo.Code.Main’ does not export ‘runUAgda’
   |
41 | import MAlonzo.Code.Main (runUAgda)
   |                           ^^^^^^^^
```
That import was introduced in #5725, but it doesn't appear in this branch, presumably this branch was forked before that was merged.  So there's no problem here, but in `master` the import fails. 

As the description for this PR says,
> Because of the restructuring of the files, Haskell programs which wish to call runUAgda should now import MAlonzo.Code.Evaluator.Term.

I'll open a new PR to do that.

**Comment by kwxm** [comment]
This should be fixed in #5747.

**Comment by mjaskelioff** [comment]
Thank you Kenneth for fixing this! great work!
